// <auto-generated />
using System;
using BlogApi.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlogApi.DataAccess.Migrations
{
    [DbContext(typeof(BlogApiContext))]
    [Migration("20260408143402_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlogApi.Domain.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("BlogApi.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e1f4769a-500c-4e5e-a86a-e39c8a954ae1",
                            CreatedAt = new DateTime(2026, 4, 8, 14, 34, 2, 119, DateTimeKind.Utc).AddTicks(3280),
                            DateAdded = new DateTime(2026, 4, 8, 14, 34, 2, 119, DateTimeKind.Utc).AddTicks(3280),
                            Email = "muhammed@test.com",
                            EmailConfirmed = false,
                            FullName = "Muhammed Yetimçok",
                            LockoutEnabled = false,
                            NormalizedEmail = "MUHAMMED@TEST.COM",
                            NormalizedUserName = "MUHAMMED",
                            PasswordHash = "AQAAAAIAAYagAAAAEF8Iiw/RBGl9CeBkTGY+/Nsgixs4GsgYdd/T5bOA3iOF7GcuPKx56RUQ4mD2PnXKNA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1bfe9eca-a37d-4598-be78-d585e22b9302",
                            TwoFactorEnabled = false,
                            UserName = "muhammed"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fb1c3a56-3c08-4b96-8839-fab7426f10ae",
                            CreatedAt = new DateTime(2026, 4, 8, 14, 34, 2, 208, DateTimeKind.Utc).AddTicks(8290),
                            DateAdded = new DateTime(2026, 4, 8, 14, 34, 2, 208, DateTimeKind.Utc).AddTicks(8290),
                            Email = "ahmet@test.com",
                            EmailConfirmed = false,
                            FullName = "Ahmet Yılmaz",
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMET@TEST.COM",
                            NormalizedUserName = "AHMET",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6ae0bd0a-4543-4476-b85a-0bb6bd9e0204",
                            TwoFactorEnabled = false,
                            UserName = "ahmet"
                        });
                });

            modelBuilder.Entity("BlogApi.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CommentId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            AppUserId = 3,
                            CreatedAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(7190),
                            PostId = 1,
                            Text = "Very helpful article!"
                        },
                        new
                        {
                            CommentId = 2,
                            AppUserId = 3,
                            CreatedAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(7190),
                            PostId = 2,
                            Text = "I would like to see more LINQ examples."
                        },
                        new
                        {
                            CommentId = 3,
                            AppUserId = 2,
                            CreatedAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(7200),
                            PostId = 3,
                            Text = "Nice explanation about Web API."
                        });
                });

            modelBuilder.Entity("BlogApi.Domain.Entities.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PostId");

                    b.HasIndex("AppUserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            AppUserId = 2,
                            Content = "This post explains the basics of C# programming language.",
                            CreateAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(6750),
                            Title = "Introduction to C#",
                            UpdateAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(6760)
                        },
                        new
                        {
                            PostId = 2,
                            AppUserId = 2,
                            Content = "This post introduces the .NET ecosystem and its core features.",
                            CreateAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(6760),
                            Title = "Getting Started with .NET",
                            UpdateAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(6760)
                        },
                        new
                        {
                            PostId = 3,
                            AppUserId = 3,
                            Content = "This post explains how to build RESTful APIs using ASP.NET Core.",
                            CreateAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(6760),
                            Title = "Building APIs with ASP.NET Core",
                            UpdateAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(6760)
                        });
                });

            modelBuilder.Entity("BlogApi.Domain.Entities.PostLike", b =>
                {
                    b.Property<int>("PostLikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostLikeId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delete")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.HasKey("PostLikeId");

                    b.HasIndex("PostId");

                    b.HasIndex("AppUserId", "PostId")
                        .IsUnique();

                    b.ToTable("PostLikes");

                    b.HasData(
                        new
                        {
                            PostLikeId = 1,
                            AppUserId = 3,
                            CreatedAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(7260),
                            PostId = 1
                        },
                        new
                        {
                            PostLikeId = 2,
                            AppUserId = 3,
                            CreatedAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(7260),
                            PostId = 2
                        },
                        new
                        {
                            PostLikeId = 3,
                            AppUserId = 2,
                            CreatedAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(7260),
                            PostId = 3
                        });
                });

            modelBuilder.Entity("BlogApi.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            CreatedAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(6700),
                            TagName = "CSharp",
                            UpdatedAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(6700)
                        },
                        new
                        {
                            TagId = 2,
                            CreatedAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(6700),
                            TagName = ".NET",
                            UpdatedAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(6700)
                        },
                        new
                        {
                            TagId = 3,
                            CreatedAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(6710),
                            TagName = "ASP.NET Core",
                            UpdatedAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(6710)
                        },
                        new
                        {
                            TagId = 4,
                            CreatedAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(6710),
                            TagName = "WebAPI",
                            UpdatedAt = new DateTime(2026, 4, 8, 14, 34, 2, 295, DateTimeKind.Utc).AddTicks(6710)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTag");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            TagId = 1
                        },
                        new
                        {
                            PostId = 1,
                            TagId = 2
                        },
                        new
                        {
                            PostId = 2,
                            TagId = 2
                        },
                        new
                        {
                            PostId = 2,
                            TagId = 3
                        },
                        new
                        {
                            PostId = 3,
                            TagId = 3
                        },
                        new
                        {
                            PostId = 3,
                            TagId = 4
                        });
                });

            modelBuilder.Entity("BlogApi.Domain.Entities.Comment", b =>
                {
                    b.HasOne("BlogApi.Domain.Entities.AppUser", "AppUser")
                        .WithMany("Comments")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogApi.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BlogApi.Domain.Entities.Post", b =>
                {
                    b.HasOne("BlogApi.Domain.Entities.AppUser", "AppUser")
                        .WithMany("Posts")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("BlogApi.Domain.Entities.PostLike", b =>
                {
                    b.HasOne("BlogApi.Domain.Entities.AppUser", "AppUser")
                        .WithMany("PostLikes")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogApi.Domain.Entities.Post", "Post")
                        .WithMany("PostLikes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("BlogApi.Domain.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("BlogApi.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("BlogApi.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("BlogApi.Domain.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogApi.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("BlogApi.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.HasOne("BlogApi.Domain.Entities.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogApi.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogApi.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostLikes");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("BlogApi.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostLikes");
                });
#pragma warning restore 612, 618
        }
    }
}
